name: CompatHelper

on:
  schedule:
    - cron: '0 0 * * *'  # ежедневно в 00:00
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.12'

      - name: Install CompatHelper
        run: |
          julia --color=yes -e '
            using Pkg
            Pkg.add("CompatHelper")
          '

      - name: Run CompatHelper
        run: |
          julia --color=yes -e '
            using CompatHelper
            CompatHelper.main()
          '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
